dataset:
  rule_count_frequency: 20
training:
  split:
    train: 0.8
    val: 0.1
    test: 0.1
  batch_size: 1024
  learning_rate_schedule:
    start_value: 0.001
    factor: 0.5
    patience: 4
  num_epochs: 100